name: Pull Request
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: deploying
      - uses: actions/setup-ssh@v2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASS}}
          port: ${{secrets.SSH_PORT}}
          scripts: |
            cd ${{ vars.DIR }}
            git pull
            composer install
          
