name: Pull Request
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ssh@v2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull changes from pull request
        run: git pull origin ${{ github.event.pull_request.head.ref }}

      - name: Add SSH key to remote
        run: echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
        shell: bash
